### PR TITLE
Update clang-format and update block indentation #30

### PR DESCRIPTION
**Pull request by alanf**
@justinseanmartin @BillZong

### CODE REVIEW

**Comment by kyleve** [comment]
:+1:

**Comment by BillZong** [comment]
XD, Cool.
I've tested it locally, and the problem is done!

**Comment by justinseanmartin** [comment]
LGTM

**Comment by alanf** [comment]
I'm going to take an alternate approach to this, since 3.9 does some things with over-indenting message sends that aren't going to fly.

**Comment by ksuther** [comment]
Did you end up using a custom build of clang-format for this change? I've found that the latest clang-format (3.8 and later) does some really horrible things to block indentation (in my opinion) and I ended up building a version with some custom patches in my own branch.

**Comment by alanf** [comment]
@ksuther 

This is the version I used:

clang-format version 3.8.0 (http://llvm.org/git/clang.git 979905788308666b0c102e5d9b5d826992d0f0ef) (http://llvm.org/git/llvm.git 569415a25bdab720be12062c3a0540ba026453db)

I'm open to using your version, and block formatting is a concern. Maybe we can see what they look like side by side?

**Comment by ksuther** [comment]
Thanks, I'll create a new issue detailing what I did and showing the differences.

**Pull request merged**
