### PR TITLE
Add test case for block formatting. #33

### PR DESCRIPTION
**Pull request by alanf**
Use custom clang-format from:
https://github.com/ksuther/spacecommander/blob/af9708b32bcc36ebc99a4e8e5b569ba2a0dcba20/bin/clang-format

@ksuther

### CODE REVIEW

**Comment by justinseanmartin** [comment]
LGTM

**Comment by natan** [comment]
LGTM

**Comment by alanf** [comment]
@ksuther which llvm SHA did you check out as part of building this? Just wanted to make sure I could build this locally

**Comment by ksuther** [comment]
I believe it's 710bb5a59841c1a3c79e32ee374b5d0448bbf9b7 (https://llvm.org/svn/llvm-project/llvm/trunk@256072).

**Pull request merged**
