### PR TITLE
Fix #42, where a trailing parameter is indented on a newline after a …

### LINKED ISSUE #42: Parameter after block literal confuses indentation
Possibly related to https://github.com/square/spacecommander/issues/40?

```
INSAFSuccessBlock INSAPIClientModelSuccessHandler(Class mantleClass, NSString *__nullable keyPath, INSHTTPSuccess __nullable success, INSHTTPFailure __nullable failure)
{
    return INSAPIClientModelSuccessChain(mantleClass, keyPath, ^(__kindof INSModel *model, id _) {
        if (success) {
            success(model);
        }
    }, failure);
}
```

Becomes:

```
INSAFSuccessBlock INSAPIClientModelSuccessHandler(Class mantleClass, NSString *__nullable keyPath, INSHTTPSuccess __nullable success, INSHTTPFailure __nullable failure)
{
    return INSAPIClientModelSuccessChain(mantleClass, keyPath, ^(__kindof INSModel *model, id _) {
        if (success) {
            success(model);
        }
    },
                                         failure);
}
```

I would prefer this not to be changed at all (i.e. not aligned), but the extraneous newline looks like a bug.

### PR DESCRIPTION
**Pull request by alanf**
…block literal.

@msanders this is based on the fix for #41, let me know how that looks

### CODE REVIEW

**Comment by msanders** [comment]
Thanks! This fixes all of the problems surrounding this in our codebase except for this edge case:

```
- (void)fetchWithSuccess:(nullable dispatch_block_t)success failure:(nullable INSHTTPFailure)failure
{
    [self GET:@"data" parameters:nil success:INSAPIClientModelArraySuccessChain([INSModel class], nil, ^(INSModel *model, id responseObject) {
        if (success) {
            success();
        }
    }, failure) failure:failure];
}
```

Which becomes:
```
- (void)fetchWithSuccess:(nullable dispatch_block_t)success failure:(nullable INSHTTPFailure)failure
{
    [self GET:@"data" parameters:nil success:INSAPIClientModelArraySuccessChain([INSModel class], nil, ^(INSModel *model, id responseObject) {
        if (success) {
            success();
        }
    },
                                                                                failure)
           failure:failure];
}
```

Here's [another diff](https://github.com/square/spacecommander/files/150386/diff.txt).

**Comment by alanf** [comment]
Thanks for the additional example, I expanded the script to match what you showed me there as well. I'm cautiously trying to minimize the what will positively match to prevent unknown side effects, so please let me know if there are more instances that we should cover.

**Comment by alanf** [comment]
@justinseanmartin can you take a look at this one too please

**Comment by justinseanmartin** [comment]
I think there may be a case for explicitly wanting params to be on the next line if you have a lot of parameters, but I think this works for now. I think we need an actual example of something that doesn't work in order to make further improvements.

Out of curiosity, how much time does it take per added python script? I'm assuming it is a trivial amount, but worth noting, because in general the linter needs to be super fast.

**Comment by justinseanmartin** [comment]
LGTM

**Comment by msanders** [comment]
Found one more edge case:

```
- (void)postWithSuccess:(nullable INSHTTPSuccess)success failure:(nullable INSHTTPFailure)failure
{
    id imageData = nil;
    [self POST:@"endpoint" parameters:nil constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
        if (imageData) {
            [formData appendPartWithFileData:imageData name:@"image" fileName:@"photo.jpg" mimeType:@"image/jpeg"];
        }
    } success:INSAPIClientEmptySuccessHandler(success) failure:failure];
}
```

Becomes:
```
- (void)postWithSuccess:(nullable INSHTTPSuccess)success failure:(nullable INSHTTPFailure)failure
{
    id imageData = nil;
    [self POST:@"endpoint" parameters:nil constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
        if (imageData) {
            [formData appendPartWithFileData:imageData name:@"image" fileName:@"photo.jpg" mimeType:@"image/jpeg"];
        }
    } success:INSAPIClientEmptySuccessHandler(success)
                          failure:failure];
}
```

Here's [the diff](https://github.com/square/spacecommander/files/152249/diff.txt).

Thanks again for looking into this so quickly.

**Comment by alanf** [comment]
@msanders want to take this for another spin? I have a potential fix for the latest edge case you pointed out, let me know if anything unexpected happens please

**Comment by orta** [comment]
This PR is awesome.

**Comment by msanders** [comment]
@alanf That seems to catch everything for us. Thanks!!

**Comment by alanf** [comment]
Thanks @msanders @justinseanmartin and @orta !

**Pull request merged**
