### PR TITLE
Add compile time check script.

### LINKED ISSUE #25: Run at compile-time?
Is it possible to run Space Commander in Xcode, possibly as a run script phase, to identify and address potential styling issues at compile-time rather than at the point of commit?

### PR DESCRIPTION
**Pull request by alanf**
Fixes #25 

@JALsnipe

### CODE REVIEW

**Comment by justinseanmartin** [comment]
Rather than running against all sources in the branch, wouldn't it be much faster for large projects to just run against `git rev-parse HEAD^`? Also, it allows for incremental fixing of style, rather than complaining about the entire repo all at once.

**Comment by JALsnipe** [comment]
Thanks @alanf!  Will check this out!

**Comment by alanf** [comment]
Since this is a compile-time check, the entire repo should be checked, just like the entire repo has to compile....Mainly, I'm considering the case where someone makes a "work in progress" commit and then tries compiling and bypasses the checks.

**Comment by alanf** [comment]
Closing since I'm not sure that there is any demand. If anyone would like compile time checks please create a new issue!

**Pull request closed without merging**
