### PR TITLE
Fix #41, Generics in category break indentation

### LINKED ISSUE #41: Generics in category break indentation
Currently this:

```
@interface NSDictionary<__covariant KeyType, __covariant ObjectType> (INSScrub)

@property (readonly, copy) NSDictionary<KeyType, ObjectType> *ins_scrubbed;

@end
```

Becomes this:

```
@interface NSDictionary <__covariant KeyType, __covariant ObjectType>
(INSScrub)

    @property(readonly, copy) NSDictionary<KeyType, ObjectType> *ins_scrubbed;

@end
```

Tried removing break penalties from the clang-format config but it seems to be unrelated. When I remove the type signature from the interface it works as expected.

### PR DESCRIPTION
**Pull request by alanf**
@msanders thanks for the bug report! Mind taking a look and seeing if this fixes the issue for you?

### CODE REVIEW

**Comment by msanders** [comment]
Thanks for such a quick response. It looks like this fixes my specific case, but there seems to be another minor problem when multiple properties are declared:

```
yam:spacecommander$ diff <(./format-objc-file-dry-run.sh Testing\ Support/UnformattedExample.m) Testing\ Support/FormattedExample.m
36c36
< @property (readonly, copy) NSDictionary<KeyType, ObjectType> *ins_scrubbedB;
---
> @property(readonly, copy) NSDictionary<KeyType, ObjectType> *ins_scrubbedB;
```

Here's a [diff](https://github.com/square/spacecommander/files/150372/diff.txt) with the two properties that fails the test.

**Comment by alanf** [comment]
@msanders I think you mean that the newlines are lost? I updated that behavior if you don't mind another look please

**Comment by msanders** [comment]
It's minor, but the thing I noticed is the implementation with one property removes the space before the attributes while the second one does not. Probably due to `clang-format` getting confused at the syntax?

**Comment by alanf** [comment]
@msanders the space removal was an accidental side effect of the script I wrote, which I have since fixed. Previously, it would strip the line, which would also remove the empty newline. In the updated version that I added today, it leaves the newline as it was.

**Comment by alanf** [comment]
@justinseanmartin mind taking a look at this PR please?

**Comment by msanders** [comment]
@alanf Actually it looks like it's the first property that gets ignored. Here's another example:

```
yam:spacecommander$ ./test.sh
Tests fail. Run
	 diff <(./format-objc-file-dry-run.sh Testing\ Support/UnformattedExample.m) Testing\ Support/FormattedExample.m 
to see why.
yam:spacecommander$ diff <(./format-objc-file-dry-run.sh Testing\ Support/UnformattedExample.m) Testing\ Support/FormattedExample.m
36c36
< @property(nonatomic, assign, getter = isWackSpacingGetter, readonly) BOOL wackSpacing;
---
> @property (nonatomic, assign, getter=isWackSpacingGetter, readonly) BOOL wackSpacing;
```

And the [diff](https://github.com/square/spacecommander/files/151556/diff.txt).

**Comment by alanf** [comment]
I see, so the first property isn't even recognized as a property, probably because the floating category name is confusing.

**Comment by alanf** [comment]
@msanders I don't have a fix for the first property being ignored. I tried re-running clang-format on just the lines that were previously ignored, but that didn't do the trick. I'll make a separate issue out of that particular case.

**Comment by justinseanmartin** [comment]
Is the spacing issue with the `@property` caused by the new python script or a pre-existing issue?

**Comment by alanf** [comment]
@justinseanmartin it's preexisting

**Comment by justinseanmartin** [comment]
LGTM

**Pull request merged**
